spring:
  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  tomcat:
    max-http-form-post-size: 5MB

app:
  host: http://localhost:8080

