spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testpass

  jpa:
    hibernate:
      ddl-auto: update


  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: shajhTest@gmail.com
    password: hpuhpitlvbgdqzho

    properties.mail.smtp:
      auth: true
      starttls.enable: true