spring:
  profiles:
    active: local


  datasource:
    url: jdbc:h2:tcp://localhost/~/studyIn
    username: sa
    password:
    driver-class-name: org.h2.Driver

  security:
    user:
      password: dsad97dsadsdsjak!#

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        #default_batch_fetch_size: 100

    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace

app.host: http://localhost:8080