spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testpass

    hikari:
      auto-commit: false

  security:
    user:
      password: dsad97dsadsdsjak!#

  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 2MB

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: shajh2210@gmail.com
    password: rkxnodxjoaacssbs

    properties.mail.smtp:
      auth: true
      starttls.enable: true